### ISSUE TITLE
What does an MVP look like?  

### ISSUE THREAD

**Issue by gbinal** [GSA/public_analytics#1]

**Comment by konklone** [comment]
cc @shawnbot @cew821 so they see the mock that @gbinal made.

@tdlowden @gbinal, in the real data right now, `weather.gov`, `mobile.weather.gov`, and `forecast.weather.gov` come up as separate entries in the top destinations. Would collapsing these together make sense?

**Comment by cew821** [comment]
Here is a more refined mockup from my first version above... the idea is a two column layout that collapses into a one-column layout. Clicking the buttons on the right would toggle the view between 7 day, 30 day and 90 day views. We can debate if these are the right time periods. I can see an argument for a 1 yr view as well (or perhaps replacing the 30 day view?).

Potentially the first page load would gather all the required data and just hide the unused views using CSS, or we could have the buttons reload new data and re-render the charts using that data if that's easier.

![image](https://cloud.githubusercontent.com/assets/1237498/5646612/4e4de1be-964c-11e4-942c-e4a00c335f8d.png)

The two column view is mostly based on the requirement of the USA.gov CMS. If we are not bound by that, we may want to consider a single column layout for simplicity's sake.

**Comment by cew821** [comment]
@konklone Regarding your "weather.gov" question, I don't think we should combine page numbers. (at least for now). I think it will be a slippery slope if we start trying to edit entries from the DAP page list to combine similar ones. We would have to document our methodology and then apply it to similar situations, which would increase editorial burden and make it challenging to keep the data consistent over time.

**Comment by tdlowden** [comment]
+1 @cew821

**Comment by gbinal** [comment]
+1

**Comment by gbinal** [comment]
(small sidenote - I should clarify that the mockup I'd posted was from @cew821)

**Comment by konklone** [comment]
Cool, yeah, and good point on the aggregation.

**Comment by konklone** [comment]
Moving this into separate issues.
