### ISSUE TITLE
Description and/or data on domain coverage of the DAP

### ISSUE THREAD

**Issue by konklone** [GSA/public_analytics#15]
@tdlowden, I know there's a lot of entropy in there, especially regarding staging domains and the like. Still, we have to at minimum have some sort of text describing what the DAP covers and how much of the .gov space is in there -- and ideally, a concrete dataset reflecting DAP's coverage.

What are your thoughts on what we can deliver here? Bear in mind, this could be driven by a dynamic export from the GA API along with everything else, it doesn't have to be manual work.

**Comment by gbinal** [comment]
I *really* think we should include some list of participating domains.  

One compromise would be to only list the 2nd level domains (x.gov) in the interim.  

I think that any shock and blowback from agencies becomes higher if we publish the list of 3rd level domains without consulting them or giving them a window of time to respond and justify leaving one off.  Of course, I actually think this is a pretty fallacious need.  Even staging domains, I'd argue, aren't that bloody secret if they are open to the public internet.

**Comment by cew821** [comment]
I agree it would be helpful to be able to point to the list of federal sites that shows which of these are participating.

**Comment by tdlowden** [comment]
I'm with @gbinal  on second-level domains. We have a few hundred, rather than the thousands of 3rd and greater level. Could be a nice way to avoid saying "this data represents X% of .govs", which is misleading, in our opinion, bc % of total .govs does not equal % of total traffic. Instead, we could say "this data is representative of a portion (but not all) of gov websites. The list is available here"

**Comment by gbinal** [comment]
As long as we are able to include the second-level domains list at launch, I think we'll be off to a great start.  As we iterate (and as agencies adjust to DAP being open), we can tackle the issue of subdomains.

**Comment by leahbannon** [comment]
I think we got this in the current about text (280 out of 1350)
