### ISSUE TITLE
Mention timezone of the data

### ISSUE THREAD

**Issue by konklone** [GSA/public_analytics#30]
I'm not certain what the timezone of the account is (I don't have view permissions), but we need to say somewhere what it is.

**Comment by konklone** [comment]
@tdlowden Is the account set to Mountain Time...?

**Comment by tdlowden** [comment]
Don't know to be honest @konklone. Will research and get back to you

**Comment by tdlowden** [comment]
We are in EST
![screen shot 2015-01-14 at 5 58 59 pm](https://cloud.githubusercontent.com/assets/6556888/5749506/88a1ee66-9c17-11e4-8aa2-6172efc55e94.png)

**Comment by konklone** [comment]
Thank you for that, @tdlowden!
