### ISSUE TITLE
Specific questions for user testing

### ISSUE THREAD

**Issue by konklone** [GSA/public_analytics#32]
Some that have come up:

* Is "yesterday's" time series data useful?
* Are we communicating browser and OS version %'s well?
* Is the difference between what's real-time and what's not clear?
* Is our wording around the nature and coverage of the DAP sensical?
* What do we need to explain with words that we can't explain with images?

**Comment by leahbannon** [comment]
* Do we need an "about" link somewhere near the top of the page, or are people comfortable finding that info by scrolling to the bottom of the page.

**Comment by leahbannon** [comment]
* Suggested user task to test: download JSON of specific data

**Comment by leahbannon** [comment]
Do you understand the difference between the live data and 7 day/30 day/90 day data?

Do you understand the difference between pages, domains, and subdomains?

**Comment by leahbannon** [comment]
https://github.com/GSA/public_analytics/blob/master/uxtesting.md
