### ISSUE TITLE
Time series showing an in-between fraction of the last hour

### ISSUE THREAD

**Issue by konklone** [GSA/public_analytics#46]
Right now we have a fraction of an hour showing, and then it gets stuck for an hour:

![visits-today](https://cloud.githubusercontent.com/assets/4592/5745942/330cc4e8-9bfa-11e4-936c-88348229a003.png)

We could actually update this every minute, even though the data is only granular to the hour. I think that's the right call.

**Comment by konklone** [comment]
(Wrong image, updated.)

**Comment by konklone** [comment]
I've made the `today` report update every minute. But it has not rectified the problem. It looks like the Core Reporting API is just not realtime - which, should be expected. This depends on figuring out the timezone (#30).

**Comment by cew821** [comment]
Related comment: could we indicate a "in-progress" hour bar different somehow? Like a different color, or a dotted line outline?

**Comment by cew821** [comment]
Alternate idea: only show hours that have already completed, and don't show an hour that is "in progress."

**Comment by konklone** [comment]
Let's not worry about this unless we have to.
