### ISSUE TITLE
Phase 2 brainstorm

### ISSUE THREAD

**Issue by gbinal** [GSA/public_analytics#6]
The initial focus is rightly on [an MVP](https://github.com/GSA/public_analytics/issues/1).  Concurrent with that, though, we should brainstorm any additions which could be very light lifts but would add to the heft of the initial release.  Share any ideas here.

**Comment by leahbannon** [comment]
Moving forward, I suggest we open unique issues for each new idea and assign them to the [Future Features milestone](https://github.com/GSA/public_analytics/milestones/Future%20features). This will make tracking/organizing/planning much easier.

**Comment by konklone** [comment]
Agreed - happy to see this re-opened if it's helpful, but now that we're all ramped up I think it'll be easier to handle things in discrete chunks.
